### ISSUE TITLE
Unable to "make" gemma binary executable on Windows

### ISSUE THREAD

**Issue by LargeLanguageModelExplorer** [google/gemma.cpp#2]
Followed the instructions given in README.md, I was able to get through all of the commands until the "make" command. It will just spit out the error "make: *** No rule to make target 'gemma'.  Stop." in the build directory. Tried doing it in the main directory ( the one above build ) and it gives out a different error "g++     gemma.cc   -o gemma process_begin: CreateProcess(NULL, g++ gemma.cc -o gemma, ...) failed. process_begin: CreateProcess(NULL, g++ gemma.cc -o gemma, ...) failed. make (e=2): The system cannot find the file specified. make: *** [<builtin>: gemma] Error 2"

Any solution to this?

**Comment by LargeLanguageModelExplorer** [comment]
Hi @austinvhuang , that is exactly what I did, everything was smooth sailing until the make part where you're trying to make an executable of gemma ( not the cmake part ). The process of Cmaking was sucessful though, I used Visual Studio 2022 for that. Here's the information you wanted, I am running pure Windows 11 and I didn't save any screenshot as I just deleted the entire folder after trying several time.

**Comment by hiccup9** [comment]
I've run it successfully on Ubuntu. Could it run on windows ？

**Comment by dcoles** [comment]
There's a few POSIX-specific APIs that currently prevent gemma.cpp from being built naively on Windows. I have #6 which addresses some of those issues so that it can be built using the optional [Clang/LLVM component of Visual Studio](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170).

Unfortunately it isn't possible to build with the regular MSVC front-end as it has a limitation where [arrays can't be more than 0x7fffffff bytes](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2148?view=msvc-170).

**Comment by dcoles** [comment]
This issue can probably be closed now that #6 has been merged.
