### ISSUE TITLE
request to remove `cmake`, `highway`, and `gtest`

### ISSUE THREAD

**Issue by 0ihsan** [google/gemma.cpp#29]
the current project dependencies, `cmake`, `highway`, and `gtest`, are impacting the ease of initial setup. they increase the overhead for new users and contributors. by considering streamlining the project to reduce the reliance, we can enhance the project's accessibility and maintainability.

**Comment by austinvhuang** [comment]
I agree cmake can be painful but the landscape of build systems + package management for C++ ... leaves something to be desired and for all its faults cmake seems to be a common denominator. What would you prefer instead?

We try to remove as many dependencies as possible, highway would be difficult since we'd have to implement portable intrinsics from scratch.

There are some things that could be simplified, eg I think the transitive footprint of sentencepiece is pretty large, if something like https://github.com/karpathy/minbpe could be swapped in that would be a win in terms of simplifying dependencies. I'd be pretty excited for that if it could be made to work.

Did you run into problems with the build process?

**Comment by jart** [comment]
I wrote a Makefile for gemma.cpp here if anyone wants it. https://github.com/jart/gemma3/blob/main/Makefile

**Comment by zeerd** [comment]
I'd suggest that use git-submodule to replace the FetchContent system. So that we could build the gamme under a system without network.

**Comment by jart** [comment]
One thing that rubbed me the wrong way about cmake was when I did a `git checkout` of a different branch inside `build/_deps/highway/` then `make` just checked out the old revision again. That's why I wrote the makefile, so I could experiment with changing transitive sources at will. I even tried using the preprocessor to roll your project up into a single 100k line stb-like header until I understood why that wouldn't be a good fit for your crtp microarchitectural support trick.

If you want the Makefile I wrote, it's yours. I'm happy to public domain it or sign any CLA you like. If you want me to send a PR, then do you want to keep cmake or should this be an additional build system sort of like what llama.cpp does? If so I'd encourage caution. Cmake isn't terrible from a user standpoint and it probably helps Microsofties who'd most likely complain about my Makefile.

**Comment by pagakarthik** [comment]
For me Gemma stood out for two reasons:
1. production / integration readiness 
2. did not have tensor flow / other dependencies - this was a a breadth of fresh air from the perspective of managing dependencies etc. 

I was under the impression that HWY enables device scalability and wasn't aware that incorporating Highway led to performance improvements - which seems to seal the deal.
It was also really interesting to see the library was sort of like a "drop in" for computations and assumed this was squarely aimed to support different device architectures in a smart fashion.

I'm not against incorporation Highway, cmake, bazel and understand their relevance. I was a little bit more keen about making the codebase "simple" and could not figure out the impact of HWY other than "device scaling".

Thank you for supporting cmake :D. 
One cool thing that I learned was the "fetch content" in CMake. This was first time I came across this implementation, and I have already written out a proposal to this feature in my other project.

**Comment by jan-wassenberg** [comment]
Thanks for sharing your impressions.
Yes, Highway is not just to allow running on any platform; we would already get that from normal C++. What it adds is access to the CPU's vector instructions, plus OpenMP-like multithreading, which we do not reliably get otherwise.

> One cool thing that I learned was the "fetch content" in CMake. This was first time I came across this implementation, and I have already written out a proposal to this feature in my other project.

Nice :) Yes, this makes dependencies considerably easier to manage.

**Comment by jan-wassenberg** [comment]
We can now avoid GUnit by building with `-DHWY_TEST_STANDALONE=1`. We're adding mention of @jart 's Makefile to the readme. Closing, feel free to reopen if you'd like to continue the discussion.
